#!/usr/bin/env python3
"""
Convert all emoji .c files from LVGL 8 LV_IMG_CF_TRUE_COLOR_ALPHA (interleaved
RGB565+alpha per pixel) to LVGL 9 LV_COLOR_FORMAT_RGB565A8 (separate RGB565
and alpha planes).

Run from the project root: python3 scripts/convert_emoji_lvgl9.py
"""

import re
import os

EMOJI_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "ui", "emoji")
SIZE = 16  # pixels (matches gen_emoji.py SIZE)


def convert_file(path):
    with open(path) as f:
        content = f.read()

    # Extract the byte array name and data
    m = re.search(
        r'static const uint8_t (\w+)_map\[\] = \{([^}]+)\}',
        content, re.DOTALL
    )
    if not m:
        print(f"  skip (no map array): {os.path.basename(path)}")
        return

    full_name = m.group(1)   # e.g. "emoji_100"
    bytes_str = m.group(2)
    bytes_data = [int(x, 16) for x in re.findall(r'0x[0-9A-Fa-f]+', bytes_str)]

    n_pixels = SIZE * SIZE
    expected = n_pixels * 3
    if len(bytes_data) != expected:
        print(f"  skip (unexpected byte count {len(bytes_data)}, want {expected}): {os.path.basename(path)}")
        return

    # Already converted (LVGL 9 file will have LV_IMAGE_HEADER_MAGIC)
    if "LV_IMAGE_HEADER_MAGIC" in content:
        print(f"  already LVGL 9: {os.path.basename(path)}")
        return

    # LVGL 8 layout: [rgb565_lo, rgb565_hi, alpha] per pixel (interleaved)
    # LVGL 9 layout: [all rgb565 bytes][all alpha bytes]  (separate planes)
    rgb_plane = []
    alpha_plane = []
    for i in range(n_pixels):
        rgb_plane.append(bytes_data[i * 3 + 0])   # lo
        rgb_plane.append(bytes_data[i * 3 + 1])   # hi
        alpha_plane.append(bytes_data[i * 3 + 2]) # alpha

    new_pixels = rgb_plane + alpha_plane
    assert len(new_pixels) == expected

    # Rebuild hex block (12 bytes per line)
    hex_rows = []
    for i in range(0, len(new_pixels), 12):
        chunk = new_pixels[i:i + 12]
        hex_rows.append("    " + ", ".join(f"0x{b:02X}" for b in chunk))
    hex_block = ",\n".join(hex_rows)

    new_content = f"""\
// Saitama — {full_name}.c
// Copyright 2026 Saitama — MIT License
// Auto-generated by scripts/gen_emoji.py — do not edit by hand.
// Source: jdecked/twemoji 16.0.1 (CC-BY 4.0, Twitter/Twemoji contributors)

#include "emoji_data.h"

static const uint8_t {full_name}_map[] = {{
{hex_block}
}};

const lv_image_dsc_t {full_name} = {{
    .header = {{
        .magic  = LV_IMAGE_HEADER_MAGIC,
        .cf     = LV_COLOR_FORMAT_RGB565A8,
        .flags  = 0,
        .w      = {SIZE},
        .h      = {SIZE},
        .stride = {SIZE * 2},
    }},
    .data_size = {len(new_pixels)},
    .data      = {full_name}_map,
}};
"""
    with open(path, "w") as f:
        f.write(new_content)
    print(f"  converted: {os.path.basename(path)}")


def main():
    c_files = sorted(
        f for f in os.listdir(EMOJI_DIR)
        if f.endswith(".c") and f != "emoji_data.h"
    )
    print(f"Converting {len(c_files)} emoji files in {EMOJI_DIR} …")
    for fname in c_files:
        convert_file(os.path.join(EMOJI_DIR, fname))
    print("Done.")


if __name__ == "__main__":
    main()
