#!/usr/bin/env python3
"""
Generate LVGL C image arrays for a curated emoji set from jdecked/twemoji 16.0.1
(community-maintained fork of Twitter Twemoji; Unicode Emoji 16.0).

Output: one .c file per emoji + emoji_data.h in src/ui/emoji/
Format: LV_IMG_CF_TRUE_COLOR_ALPHA  →  [RGB565_lo, RGB565_hi, alpha] per pixel

Run from the project root:  python3 scripts/gen_emoji.py
"""

import os
import struct
import urllib.request
from PIL import Image
import io

SIZE = 16  # pixels (fits within montserrat_14 line_height=18)

# (symbol_name, primary_codepoint, filename_on_CDN)
#
# For multi-codepoint emoji (flags, sequences) the primary_codepoint is the
# FIRST codepoint LVGL will look up.  The remainder of the sequence is ignored
# by the imgfont system — the second codepoint renders as nothing from the
# fallback font, which is acceptable at this screen size.
#
# England 🏴󠁧󠁢󠁥󠁮󠁧󠁿 and Wales 🏴󠁧󠁢󠁷󠁬󠁳󠁿 both begin with U+1F3F4 (black-flag base).
# Only one can be registered per codepoint — we use the Wales dragon image
# (more visually distinctive at 16 px).  The England image is downloaded as
# emoji_england.c for future use but is NOT in the lookup table.
EMOJI = [
    # ── original 15 ──────────────────────────────────────────────────────────
    ("joy",        0x1F602, "1f602"),       # 😂
    ("heart",      0x2764,  "2764"),        # ❤️
    ("rofl",       0x1F923, "1f923"),       # 🤣
    ("thumbsup",   0x1F44D, "1f44d"),       # 👍
    ("sob",        0x1F62D, "1f62d"),       # 😭
    ("pray",       0x1F64F, "1f64f"),       # 🙏
    ("smile",      0x1F60A, "1f60a"),       # 😊
    ("heart_eyes", 0x1F60D, "1f60d"),       # 😍
    ("fire",       0x1F525, "1f525"),       # 🔥
    ("sunglasses", 0x1F60E, "1f60e"),       # 😎
    ("tada",       0x1F389, "1f389"),       # 🎉
    ("cry",        0x1F622, "1f622"),       # 😢
    ("skull",      0x1F480, "1f480"),       # 💀
    ("wave",       0x1F44B, "1f44b"),       # 👋
    ("check",      0x2705,  "2705"),        # ✅
    # ── render-only additions ─────────────────────────────────────────────────
    ("frog",       0x1F438, "1f438"),       # 🐸
    ("sparkles",   0x2728,  "2728"),        # ✨  starlight / sparkles
    ("wales",      0x1F3F4, "1f3f4-e0067-e0062-e0077-e006c-e0073-e007f"),  # 🏴󠁧󠁢󠁷󠁬󠁳󠁿 Wales (U+1F3F4 — also fires for 🏴󠁧󠁢󠁥󠁮󠁧󠁿)
    ("ireland",    0x1F1EE, "1f1ee-1f1ea"), # 🇮🇪 first CP of sequence
    ("cat_joy",    0x1F639, "1f639"),       # 😹
    ("dog",        0x1F415, "1f415"),       # 🐕
    ("satellite",  0x1F4E1, "1f4e1"),       # 📡
    ("us_flag",    0x1F1FA, "1f1fa-1f1f8"), # 🇺🇸 first CP of sequence
    ("house",      0x1F3E0, "1f3e0"),       # 🏠
    # ── second batch ─────────────────────────────────────────────────────────
    ("dizzy",      0x1F4AB, "1f4ab"),       # 💫  dizzy / starlight swirl
    ("robot",      0x1F916, "1f916"),       # 🤖
    ("car",        0x1F697, "1f697"),       # 🚗
    ("moto",       0x1F3CD, "1f3cd"),        # 🏍️
    ("plane",      0x2708,  "2708"),        # ✈️
    ("ship",       0x1F6A2, "1f6a2"),       # 🚢
    ("palm",       0x1F334, "1f334"),       # 🌴
    ("house2",     0x1F3E1, "1f3e1"),       # 🏡  house with garden
]

# Downloaded but NOT registered in the lookup table (codepoint collision).
EMOJI_EXTRA = [
    ("england", "1f3f4-e0067-e0062-e0065-e006e-e0067-e007f"),  # 🏴󠁧󠁢󠁥󠁮󠁧󠁿 England (shares U+1F3F4 with Wales above)
]

CDN = "https://cdn.jsdelivr.net/gh/jdecked/twemoji@16.0.1/assets/72x72/{}.png"

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "ui", "emoji")
os.makedirs(OUT_DIR, exist_ok=True)


def rgb_to_rgb565_le(r, g, b):
    """Return (lo, hi) bytes of little-endian RGB565."""
    rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return rgb565 & 0xFF, (rgb565 >> 8) & 0xFF


def fetch_and_convert(cdn_name):
    url = CDN.format(cdn_name)
    with urllib.request.urlopen(url, timeout=10) as resp:
        data = resp.read()
    img = Image.open(io.BytesIO(data)).convert("RGBA")
    img = img.resize((SIZE, SIZE), Image.LANCZOS)
    pixels = []
    for py in range(SIZE):
        for px in range(SIZE):
            r, g, b, a = img.getpixel((px, py))
            lo, hi = rgb_to_rgb565_le(r, g, b)
            pixels.extend([lo, hi, a])
    return pixels


def write_c_file(sym, codepoint, pixels):
    name = f"emoji_{sym}"
    path = os.path.join(OUT_DIR, f"{name}.c")
    n = len(pixels)
    hex_rows = []
    for i in range(0, n, 12):
        chunk = pixels[i:i+12]
        hex_rows.append("    " + ", ".join(f"0x{b:02X}" for b in chunk))
    hex_block = ",\n".join(hex_rows)

    src = f"""\
// Saitama — {name}.c
// Copyright 2026 Saitama — MIT License
// Auto-generated by scripts/gen_emoji.py — do not edit by hand.
// Source: jdecked/twemoji 16.0.1 (CC-BY 4.0, Twitter/Twemoji contributors)

#include "emoji_data.h"

static const uint8_t {name}_map[] = {{
{hex_block}
}};

const lv_img_dsc_t {name} = {{
    .header = {{
        .cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .always_zero = 0,
        .reserved    = 0,
        .w           = {SIZE},
        .h           = {SIZE},
    }},
    .data_size = {n},
    .data      = {name}_map,
}};
"""
    with open(path, "w") as f:
        f.write(src)
    print(f"  wrote {path}  ({n} bytes)")


def write_header():
    path = os.path.join(OUT_DIR, "emoji_data.h")
    decls = "\n".join(
        f"extern const lv_img_dsc_t emoji_{sym};"
        for sym, _, _ in EMOJI
    )
    entries = "\n".join(
        f"    {{ 0x{cp:05X}u, &emoji_{sym} }},"
        for sym, cp, _ in EMOJI
    )
    src = f"""\
// Saitama — emoji_data.h
// Copyright 2026 Saitama — MIT License
// Auto-generated by scripts/gen_emoji.py — do not edit by hand.

#pragma once
#include <lvgl.h>

#ifdef __cplusplus
extern "C" {{
#endif

{decls}

#ifdef __cplusplus
}}
#endif

// Lookup table used by Emoji.cpp
typedef struct {{ uint32_t codepoint; const lv_img_dsc_t* img; }} OpsEmojiEntry;
static const OpsEmojiEntry kOpsEmoji[] = {{
{entries}
}};
static const int kOpsEmojiCount = {len(EMOJI)};
"""
    with open(path, "w") as f:
        f.write(src)
    print(f"  wrote {path}")


print(f"Downloading and converting {len(EMOJI)} registered + {len(EMOJI_EXTRA)} extra emoji at {SIZE}x{SIZE}px …")
for sym, cp, cdn_name in EMOJI:
    print(f"  {cdn_name} (U+{cp:04X}) …", end=" ", flush=True)
    try:
        px = fetch_and_convert(cdn_name)
        write_c_file(sym, cp, px)
        print("ok")
    except Exception as e:
        print(f"FAILED: {e}")

for sym, cdn_name in EMOJI_EXTRA:
    print(f"  {cdn_name} (extra, not registered) …", end=" ", flush=True)
    try:
        px = fetch_and_convert(cdn_name)
        # Use codepoint 0 as a placeholder — this entry is never in the lookup.
        write_c_file(sym, 0, px)
        print("ok")
    except Exception as e:
        print(f"FAILED: {e}")

write_header()
print("Done.")
