// Saitama — emoji_data.h
// Copyright 2026 Saitama — MIT License
// Auto-generated by scripts/gen_emoji.py — do not edit by hand.

#pragma once
#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_img_dsc_t emoji_joy;
extern const lv_img_dsc_t emoji_heart;
extern const lv_img_dsc_t emoji_rofl;
extern const lv_img_dsc_t emoji_thumbsup;
extern const lv_img_dsc_t emoji_sob;
extern const lv_img_dsc_t emoji_pray;
extern const lv_img_dsc_t emoji_smile;
extern const lv_img_dsc_t emoji_heart_eyes;
extern const lv_img_dsc_t emoji_fire;
extern const lv_img_dsc_t emoji_sunglasses;
extern const lv_img_dsc_t emoji_tada;
extern const lv_img_dsc_t emoji_cry;
extern const lv_img_dsc_t emoji_skull;
extern const lv_img_dsc_t emoji_wave;
extern const lv_img_dsc_t emoji_check;
extern const lv_img_dsc_t emoji_frog;
extern const lv_img_dsc_t emoji_sparkles;
extern const lv_img_dsc_t emoji_wales;
extern const lv_img_dsc_t emoji_ireland;
extern const lv_img_dsc_t emoji_cat_joy;
extern const lv_img_dsc_t emoji_dog;
extern const lv_img_dsc_t emoji_satellite;
extern const lv_img_dsc_t emoji_us_flag;
extern const lv_img_dsc_t emoji_house;
extern const lv_img_dsc_t emoji_dizzy;
extern const lv_img_dsc_t emoji_robot;
extern const lv_img_dsc_t emoji_car;
extern const lv_img_dsc_t emoji_moto;
extern const lv_img_dsc_t emoji_plane;
extern const lv_img_dsc_t emoji_ship;
extern const lv_img_dsc_t emoji_palm;
extern const lv_img_dsc_t emoji_house2;

#ifdef __cplusplus
}
#endif

// Lookup table used by Emoji.cpp
typedef struct { uint32_t codepoint; const lv_img_dsc_t* img; } OpsEmojiEntry;
static const OpsEmojiEntry kOpsEmoji[] = {
    { 0x1F602u, &emoji_joy },
    { 0x02764u, &emoji_heart },
    { 0x1F923u, &emoji_rofl },
    { 0x1F44Du, &emoji_thumbsup },
    { 0x1F62Du, &emoji_sob },
    { 0x1F64Fu, &emoji_pray },
    { 0x1F60Au, &emoji_smile },
    { 0x1F60Du, &emoji_heart_eyes },
    { 0x1F525u, &emoji_fire },
    { 0x1F60Eu, &emoji_sunglasses },
    { 0x1F389u, &emoji_tada },
    { 0x1F622u, &emoji_cry },
    { 0x1F480u, &emoji_skull },
    { 0x1F44Bu, &emoji_wave },
    { 0x02705u, &emoji_check },
    { 0x1F438u, &emoji_frog },
    { 0x02728u, &emoji_sparkles },
    { 0x1F3F4u, &emoji_wales },
    { 0x1F1EEu, &emoji_ireland },
    { 0x1F639u, &emoji_cat_joy },
    { 0x1F415u, &emoji_dog },
    { 0x1F4E1u, &emoji_satellite },
    { 0x1F1FAu, &emoji_us_flag },
    { 0x1F3E0u, &emoji_house },
    { 0x1F4ABu, &emoji_dizzy },
    { 0x1F916u, &emoji_robot },
    { 0x1F697u, &emoji_car },
    { 0x1F3CDu, &emoji_moto },
    { 0x02708u, &emoji_plane },
    { 0x1F6A2u, &emoji_ship },
    { 0x1F334u, &emoji_palm },
    { 0x1F3E1u, &emoji_house2 },
};
static const int kOpsEmojiCount = 32;
